name = input("enter your name: ")
age = input("enter your age: ")
college = input("enter your college: ")
branch = input("enter your branch: ")
print("enter the first no.: ")
print("enter thr second no.: ")
print("sum:", num1+num2)
print("diference:", num1-num2)
print("product:", num1*num2)
print("quotient:", num1/num2)

print(name)
print(age)
print(college)
print(branch)
