import pandas as pd
df = pd.read_csv("day20_retail_orders_messy.csv")
print(df)
print(df.duplicated())
df = df.drop_duplicates()
print(df.isnull().sum())
df["Price"]=df["Price"].fillna(0)
df["Quantity"]=df["Quantity"].fillna(0)
df["City"]= df["City"].str.title()
df["Product"] = df["Product"].str.strip()
df["Product"] = df["Product"].str.title()
df["Payment"] = df["Payment"].str.upper()
df["Revenue"] = df["Quantity"]*df["Price"]
df.groupby("Product")["Revenue"].sum()
print(df.groupby("Product")["Revenue"].sum().sort_values(ascending=False))
print(df.groupby("City")["Revenue"].sum().sort_values(ascending=False))
print(df.groupby("Customer")["Revenue"].sum().sort_values(ascending=False))
print(df.groupby("Payment")["Revenue"].sum().sort_values(ascending=False))
print(df.sort_values("Revenue", ascending=False).head(3))
