import pandas as pd 
df = pd.read_csv("day19_sales_data.csv")
print(df.head())
print(df.shape)
print(df.columns)
print(df.info())
print(df.describe())
print(df["Product"].value_counts())
df["Revenue"] = df["Quantity"]*df["Price"]
print(df) 
print(df.groupby("Product")["Revenue"].sum())
print(df.groupby("City")["Revenue"].sum())
print(df["City"].value_counts())
print(df[df["City"] == "Chennai"])
print(df[df["City"] == "Bangalore"])
print(df.groupby("Customer")["Revenue"].sum())
print(df[df["Customer"] == "Asha"])
print(df.groupby("Payment")["Revenue"].sum())
print(df.sort_values("Revenue", ascending=False).head(3))